version: "2"
services:
  common: 
    {
      baseip: 0.0.0.0, port: 9010, xgfaceaddr: xgface:50000, deadline: 5,
      logLevel: "InfoLevel",  #PanicLevel FatalLevel ErrorLevel WarnLevel InfoLevel DebugLevel TraceLevel
      mysql: { host: mysql:3306, user: "puppy", password: "123456", database: "xgface", gormlogmode: false },
      redis: { host: redis:6379, user: "root", password: "" },
      cpuThreshold: 11,
      gpuThreshold: 12,
      memoryThreshold: 13,
      diskThreshold: 14,
    }
