# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/video_show_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_video_show(object):
    def setupUi(self, video_show):
        video_show.setObjectName("video_show")
        video_show.resize(1101, 818)
        self.gridLayout = QtWidgets.QGridLayout(video_show)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalWidget = QtWidgets.QWidget(video_show)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalWidget_1 = QtWidgets.QWidget(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_1.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_1.setSizePolicy(sizePolicy)
        self.horizontalWidget_1.setObjectName("horizontalWidget_1")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout(self.horizontalWidget_1)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.show_label = QtWidgets.QLabel(self.horizontalWidget_1)
        self.show_label.setFrameShape(QtWidgets.QFrame.Box)
        self.show_label.setLineWidth(1)
        self.show_label.setText("")
        self.show_label.setObjectName("show_label")
        self.horizontalLayout_1.addWidget(self.show_label)
        self.verticalLayout_2.addWidget(self.horizontalWidget_1)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_2.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_2.setSizePolicy(sizePolicy)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalWidget_3 = QtWidgets.QWidget(self.horizontalWidget_2)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.status_label = QtWidgets.QLabel(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setMinimumSize(QtCore.QSize(0, 30))
        self.status_label.setFrameShape(QtWidgets.QFrame.Box)
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.horizontalLayout_3.addWidget(self.status_label)
        self.display_label = QtWidgets.QLabel(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_label.sizePolicy().hasHeightForWidth())
        self.display_label.setSizePolicy(sizePolicy)
        self.display_label.setMinimumSize(QtCore.QSize(0, 30))
        self.display_label.setFrameShape(QtWidgets.QFrame.Box)
        self.display_label.setText("")
        self.display_label.setObjectName("display_label")
        self.horizontalLayout_3.addWidget(self.display_label)
        self.time_label = QtWidgets.QLabel(self.horizontalWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_label.sizePolicy().hasHeightForWidth())
        self.time_label.setSizePolicy(sizePolicy)
        self.time_label.setMinimumSize(QtCore.QSize(0, 30))
        self.time_label.setFrameShape(QtWidgets.QFrame.Box)
        self.time_label.setText("")
        self.time_label.setObjectName("time_label")
        self.horizontalLayout_3.addWidget(self.time_label)
        self.horizontalLayout_2.addWidget(self.horizontalWidget_3)
        self.horizontalWidget_4 = QtWidgets.QWidget(self.horizontalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget_4.sizePolicy().hasHeightForWidth())
        self.horizontalWidget_4.setSizePolicy(sizePolicy)
        self.horizontalWidget_4.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalWidget_4.setObjectName("horizontalWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.filename_label = QtWidgets.QLabel(self.horizontalWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filename_label.sizePolicy().hasHeightForWidth())
        self.filename_label.setSizePolicy(sizePolicy)
        self.filename_label.setMinimumSize(QtCore.QSize(0, 30))
        self.filename_label.setFrameShape(QtWidgets.QFrame.Box)
        self.filename_label.setText("")
        self.filename_label.setObjectName("filename_label")
        self.horizontalLayout_4.addWidget(self.filename_label)
        self.horizontalLayout_2.addWidget(self.horizontalWidget_4)
        self.verticalLayout_2.addWidget(self.horizontalWidget_2)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.verticalWidget_2 = QtWidgets.QWidget(video_show)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_2.sizePolicy().hasHeightForWidth())
        self.verticalWidget_2.setSizePolicy(sizePolicy)
        self.verticalWidget_2.setMinimumSize(QtCore.QSize(125, 0))
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(-1, 1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.verticalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 350))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.open_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_button.sizePolicy().hasHeightForWidth())
        self.open_button.setSizePolicy(sizePolicy)
        self.open_button.setMinimumSize(QtCore.QSize(80, 30))
        self.open_button.setMaximumSize(QtCore.QSize(80, 30))
        self.open_button.setObjectName("open_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.open_button)
        self.play_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_button.sizePolicy().hasHeightForWidth())
        self.play_button.setSizePolicy(sizePolicy)
        self.play_button.setMinimumSize(QtCore.QSize(80, 30))
        self.play_button.setMaximumSize(QtCore.QSize(80, 30))
        self.play_button.setObjectName("play_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.play_button)
        self.encode_video_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encode_video_button.sizePolicy().hasHeightForWidth())
        self.encode_video_button.setSizePolicy(sizePolicy)
        self.encode_video_button.setMinimumSize(QtCore.QSize(80, 30))
        self.encode_video_button.setMaximumSize(QtCore.QSize(80, 30))
        self.encode_video_button.setObjectName("encode_video_button")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.encode_video_button)
        self.encode_jpg_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.encode_jpg_button.sizePolicy().hasHeightForWidth())
        self.encode_jpg_button.setSizePolicy(sizePolicy)
        self.encode_jpg_button.setMinimumSize(QtCore.QSize(80, 30))
        self.encode_jpg_button.setMaximumSize(QtCore.QSize(80, 30))
        self.encode_jpg_button.setObjectName("encode_jpg_button")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.encode_jpg_button)
        self.set_fps_line = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_fps_line.sizePolicy().hasHeightForWidth())
        self.set_fps_line.setSizePolicy(sizePolicy)
        self.set_fps_line.setMinimumSize(QtCore.QSize(80, 20))
        self.set_fps_line.setMaximumSize(QtCore.QSize(80, 20))
        self.set_fps_line.setObjectName("set_fps_line")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.set_fps_line)
        self.set_fps_button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_fps_button.sizePolicy().hasHeightForWidth())
        self.set_fps_button.setSizePolicy(sizePolicy)
        self.set_fps_button.setMinimumSize(QtCore.QSize(80, 30))
        self.set_fps_button.setMaximumSize(QtCore.QSize(80, 30))
        self.set_fps_button.setObjectName("set_fps_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.set_fps_button)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.open_cfg_button = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_cfg_button.sizePolicy().hasHeightForWidth())
        self.open_cfg_button.setSizePolicy(sizePolicy)
        self.open_cfg_button.setMinimumSize(QtCore.QSize(80, 30))
        self.open_cfg_button.setMaximumSize(QtCore.QSize(80, 30))
        self.open_cfg_button.setObjectName("open_cfg_button")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.open_cfg_button)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.verticalWidget_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(video_show)
        QtCore.QMetaObject.connectSlotsByName(video_show)

    def retranslateUi(self, video_show):
        _translate = QtCore.QCoreApplication.translate
        video_show.setWindowTitle(_translate("video_show", "video_show"))
        self.groupBox.setTitle(_translate("video_show", "视频"))
        self.open_button.setText(_translate("video_show", "打开"))
        self.play_button.setText(_translate("video_show", "开始"))
        self.encode_video_button.setText(_translate("video_show", "上一帧"))
        self.encode_jpg_button.setText(_translate("video_show", "下一帧"))
        self.set_fps_button.setText(_translate("video_show", "帧率"))
        self.groupBox_2.setTitle(_translate("video_show", "配置"))
        self.open_cfg_button.setText(_translate("video_show", "打开"))

