# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBoxWebUITest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_boxWebUITest(self):
    # Test name: BoxWebUITest
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("http://10.58.122.201/")
    # 2 | setWindowSize | 662x458 |  | 
    self.driver.set_window_size(662, 458)
    # 3 | click | name=username |  | 
    self.driver.find_element(By.NAME, "username").click()
    # 4 | type | name=username | admin | 
    self.driver.find_element(By.NAME, "username").send_keys("admin")
    # 5 | click | css=.main_right |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".main_right").click()
    # 6 | click | name=password |  | 
    self.driver.find_element(By.NAME, "password").click()
    # 7 | type | name=password | 123456 | 
    self.driver.find_element(By.NAME, "password").send_keys("123456")
    # 8 | click | css=.el-button |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".el-button").click()
    # 9 | mouseOver | css=.el-button |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | click | css=.cam-photo .title |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".cam-photo .title").click()
  
