# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium import webdriver
# class TestTest():
#   def setup_method(self, method):
#     self.driver = webdriver.Chrome()
#     self.vars = {}
#
#   def teardown_method(self, method):
#     self.driver.quit()
  
def test_test(driver):
  driver.get("http://10.58.122.201/")
  #driver.set_window_size(666, 458)
  time.sleep(0.5)
  #driver.find_element(By.NAME, "username").click()
  driver.find_element(By.NAME, "username").send_keys("admin")
  #driver.find_element(By.NAME, "password").click()
  driver.find_element(By.NAME, "password").send_keys("123456")
  driver.find_element(By.CSS_SELECTOR, ".el-button").click()

if __name__ == "__main__":
  driver = webdriver.Chrome()
  test_test(driver)